_target_: pytorch_lightning.loggers.WandbLogger
save_dir: .
name: gmm_sac_${skill.name}_${gmm.name}
group: gmm_sac
log_model: false
project: Project-RL-Manipulator-Arm
# entity: null  # uncomment + set "your-wandb-username" if you want a team/personal space
id: null      # setup_logger() lo setea = name; la key debe existir (OmegaConf struct mode)
